---
output: html_notebook
bibliography: references.bib
---

## Description and sources for simulation parameters

### Model structure

The basic model structure is inspired by many studies on the natural clinical progression of COVID-19 infection. For a nice summary, see [@wu_characteristics_2020]. Infected individuals do not immediately develop severe symptoms, but instead pass through milder phases of infection first. In some studies, what we call *mild* infections are grouped into two different categories, *mild* and *moderate*, where individuals with *moderate* infection show radiographic signs of mild pneumonia. These *mild* and *moderate* cases occur at roughly equal proportions (for ex. see @yang_epidemiological_2020). There is some debate about the role of pre-symptomatic transmission (occuring from exposed stage) and asymptomatic infection and transmission for COVID-19. The current model version does not include these effects. 

### Dynamic model parameters

The behavior of the dynamic model is determined by a set of rate parameters, including the transmission rates $\beta_i$, the progression rates $a$ and $p_i$, the recovery rates $\gamma_i$, and the death rate $\mu$. While these rates themselves are not generally measured directly in studies, other quantities that are measurable can be used to back out these rate parameters. 

The time spent in the exposed class is called the *incubation period* and is generally assumed to be equal to the time between exposure to an infected source and the development of symptoms. In the model the average incubation period is $1/a$. 

The *infectious period* is the time during which an individual can transmit to others. In our model there are potentially three different infectious periods, occuring during each clinical stage of infection ($I_1$, $I_2$, $I_3$). We need to know the duration of each of these stages. We think it's likely that an individual is most infectious during the stage of mild infection, when they would still be in the community and feeling well enough to interact with others, but in the model there is also the option for transmission in the other stages, for example transmission from hospitalized patients to their healthcare providers. At a population level, we expect most transmission to occur from these individuals with mild infection, since most patients do not progress past this stage.  For COVID-19 we can estimate the duration of the first stage from a) the duration of mild symptoms, b) the time from symptom onset to hospitalization (e.g. progress to severe stage), or c) the duration of viral shedding via sputum or throat swabs, d) the serial interval between symptom onset in an index case and a secondary case they infect. In the model the quantities a)-c) equal $1/(p_1 + \gamma_1)$, whereas d) is $1/a + (1/2) 1/(p_1 + \gamma_1)$. These estimates converge on similar values for $p_1+\gamma_1$.  The probability of progressing to the *severe* stage is equal to the proportion of all infections that end up being either severe or critical, and must equal the parameter combination $p_1/(p_1+\gamma_1)$. 

Individuals with severe infection ($I_2$) require hospitalization. The duration of severe infections, which could be reported as the time from hospital admission to recovery for individuals who did not progress to the critical stage, or the time from hospital admission to ICU admission (since critical cases require ICU-level care), corresponds to the model parameters $1/(p_2+\gamma_2)$. Since there are not direct estimates of this duration, we instead used estimates of the total time from symptom onset to ICU-admission (e.g. combined length of mild + severe infection), and subtracted the infered duration of mild infection. Then we used the observed probability of progressing to critical infection, equal to the ratio of critical to critical + severe infections, which equals $p_2/(p_2 + \gamma_2$), to separately work out $p_2$ and $\gamma_2$. At the critical infection stage ($I_3$) ICU care, generally with mechanical ventilation, is required. The duration of this stage of infection, e.g. the time from ICU admission to recovery or death, is equal to $1/(\gamma_3 + \mu$) but not often reported. Instead, studies often report the total time from hospital admission to death, which can approximate the sum of the duration of the severe and critical stages. Thus by subtracting the duration of $I_2$, the duration of $I_3$ can be estimated. The observed case fatality ratio (CFR) describes the fraction of all symptomatic infected individuals who eventually die. Since individuals must progress to critical infection to die, the conditional probability of someone in the critical stage dying vs recovering is given by the CFR divided by the fraction of all infections that are severe. This must equal the model parameter combination $\mu/(\gamma_3 + \mu)$. 

Table 1 summarizes the literature sources we used to estimate default values for all these model parameters. An updated list is also available in this [Google Doc](https://docs.google.com/spreadsheets/d/1zZKKnZ47lqfmUGYDQuWNnzKnh-IDMy15LBaRmrBcjqE). Users can choose their own values based on other studies or particular regional contexts. 

__Table 1__:  Estimated parameters for COVID-19 clinical progression, and literature sources

Quantity                                 Parameter                              Value        Source       
--------------------------------------   ---------------------                  ----------   --------------------------------------------------
Incubation Period                         $1/a$                                 5 days       [@li_early_2020 ; @linton_incubation_2020; @lauer_incubation_2020; @bi_epidemiology_2020; @sanche_novel_2020]
Proportion of mild infections             $\gamma_1/(p_1+\gamma_1)$             80%          [@wu_characteristics_2020; @yang_epidemiological_2020; @liu_nl_2020]
Duration of mild infections               $1/(p_1+\gamma_1)$                    6 days       Viral shedding: [@woelfel_clinical_2020], Time from symptoms to hospitalization: [@sanche_novel_2020; @tindale_transmission_2020]
Proportion of severe infections           $\gamma_1/(p_1+\gamma_1)$             15%          [@wu_characteristics_2020; @yang_epidemiological_2020]
Time from symptoms to ICU admission       --                                    12 days      [@huang_clinical_2020; @yang_clinical_2020; @liu_nl_2020; @zhou_clinical_2020]
Duration of severe infection              $1/(p_2+\gamma_2)$                    6 days       =[Time from symptoms to ICU admit] - [Duration of mild infections]
Proportion of critical infections         % Severe$\times p_2/(p_2+\gamma_2)$   5%           [@wu_characteristics_2020; @yang_epidemiological_2020; @liu_nl_2020]
Time from hospital admission to death     --                                    14 days      [@sanche_novel_2020; @linton_incubation_2020;@zhou_clinical_2020;  @guan_clinical_2020]
Duration of critical infection            $1/(\mu+\gamma_3)$                    8 days       =[Time from hospital admit to death] - [Duration of severe infections] [@zhou_clinical_2020]
Time from symptom onset to death          --                                    20 days      =[Duration mild + severe + critical infections][@wu_estimating_2020; @verity_estimates_2020; @zhou_clinical_2020]
Case fatality ratio                       % Critical$\times\mu/(\mu+\gamma_3)$  2%           [@wu_characteristics_2020; @russell_estimating_2020; @riou_adjusted_2020; @baud_real_2020; @wu_estimating_2020; @verity_estimates_2020]
Serial interval                           $1/a + (1/2) 1/(p_1 + \gamma_1)$      8 days       =[Incubation Period]+1/2[Duration of mild infection]

The rates of transmission are generally impossible to directly observe or estimate. Instead, these values can be backed out by looking at the early exponential growth rate ($r$) of an epidemic and choosing transmission rates that recreate these observations. The growth of COVID-19 outbreaks has varied a lot between settings and over time. Some values reported in the literature are in Table 2. Real-time automated calculation of growth rates for different countries is available with Ben Phillip's [Coronavirus Forecast Shiny App](https://benflips.shinyapps.io/nCovForecast/) or from the [Centre for Mathematical Modelling of Infectious Diseases](https://cmmid.github.io/topics/covid19/current-patterns-transmission/global-time-varying-transmission.html). The default values for the simulation are currently set to match a situation with $r=0.14$ [@verity_estimates_2020]. As a default we assume that the dominant source of transmission is from individuals with mild infections (e.g. $\beta_1 \gg \beta_2, \beta_3$), who are likely to still be in the community, as opposed to isolated in the hospital. 

Some recent reports have suggested that healthcare workers are disproportionally infected with COVID-19, suggesting there is some role to hospital-based transmission (e.g. from individuals in states $I_2$ and $I_3$, or individuals who are hospitalized with only mild infection). In China, approximately 5% of all infections were in healthcare workers [@wang_exploring_2020], and in Italy the number is currently around 10% [@wang_exploring_2020]. To capture this, we choose to include a small contribution of $\beta_2$ and $\beta_3$ to transmission such with baseline values of our other parameters around 10% of the value of $R_0$ was due to transmission from severe + critical infections.

__Table 2__: Observed early epidemic growth rates $r$ across different settings, along with the corresponding doubling times. There are many other settings where growth rates are now close to zero. 

Growth rate $r$   Doubling time  Location        Dates           Source
---------------- --------------  --------------  --------------- -------------------------
0.1               6.9 days        Wuhan           Early January   [@li_early_2020]
0.14              5.0 days        Wuhan           Early January   [@verity_estimates_2020]
0.25              2.8 days        Wuhan           January         [@zhao_analysis_2020]
0.3               2.3 days        Wuhan           January         [@sanche_novel_2020]
0.5               1.4 days        Italy           Feb 24          [@abbott_temporal_2020]
0.17              4.1 days        Italy           Mar 9           [@abbott_temporal_2020]
0.3               2.3 days        Iran            Mar 2           [@abbott_temporal_2020]
0.5               1.4 days        Spain           Feb 29          [@abbott_temporal_2020]
0.2               3.5 days        Spain           Mar 9           [@abbott_temporal_2020]
0.2               3.5 days        France          Mar 9           [@abbott_temporal_2020]
0.2               3.5 days        South Korea     Feb 24          [@abbott_temporal_2020]
0.5               1.4 days        UK              Mar 2           [@abbott_temporal_2020]


### Hospital capacity parameters

One of the biggest dangers of a widespread COVID-19 epidemic is the strain it could place on hospital resources, since individuals with severe and critical infection require hospital care. The critical stage of infection requires mechanical ventilation, which is ICU-level care. Severe infection can be treated in a regular hospital ward. Individuals with mild infection do not require hospitalization, and could recover at home on their own. However, in many countries these individuals have also been hospitalized, likely as a way to isolate them and reduce transmission, as well as to monitor them for progression to more aggressive disease stages. 

The default hospital capacity parameters are estimated for the US, and are expressed as resources per capita. The available hospital beds (in regular wards or on ICU floors) depends on the total number of beds that exist as well as the occupancy level. During flu season (winter months), occupancy levels are generally higher. We report the number of *available* (e.g. unoccupied) beds of both types (Table 3). 
Studies in the pandemic preparedness literature have examined how the capacity to delivery mechanical ventilation during a respiratory pathogen outbreak could be expanded beyond the traditional ICU-bed capacity (aka *conventional capacity*) by using stockpiled ventilators, non-specialist hospital staff, and retro-fitting other hospital rooms [@ajao_assessing_2015]. These expanded delivery levels are called *contingency* and *crisis* capacity. 

__Table 3__. US hospital capacity. Values are for adults beds only.

Quantity                                        Total      Per 1000 ppl    Source
---------------------------------------------   ---------  -------------   -----------------------
Hospital beds                                   900,000     2.8            [@nchs_table_2017]
Occupancy                                       66%                        [@nchs_table_2017]
ICU beds                                        80,000      0.26           [@sccm_2010]
Occupancy                                       68%                        [@sccm_2010]
$\uparrow$ flu season occupany                  7%                         [@ajao_assessing_2015]
Available hospital beds                         264,000     0.82           From above     
Available ICU beds                              22,000      0.071          From above  
Conventional Mechanical Ventilation Capacity    20,000      0.062          [@ajao_assessing_2015]
Contingency Mechanical Ventilation Capacity     50,000      0.15           [@ajao_assessing_2015]
Critical Mechanical Ventilation Capacity        135,000     0.24           [@ajao_assessing_2015]

### Updates

#### Mar 21 2020

The model now includes the possibility of __asymptomatic infection__. In most original COVID-19 studies, nearly all individuals included had symptoms, since the presence of symptoms was used to determine whether someone would be administered a test for COVID-19. However, it is possible that some individuals may be infected and be able to transmit to others without developing symptoms. Recent evidence from has suggested this is the case, as new studies have emerged in which asymptomatic individuals were also screened for infection and tested positive. We take estimates of $f$, the fraction of infections that are asymptomatic, from the literature, and assume that asymptomatic infections have the same length and the same transmission rate as symptomatic infections. 

The model now also includes the possibility of __pre-symptomatic transmission__. In general compartmental epidemiological models assume that the onset of symptoms and the onset of infectiousness coincide, but recent evidence suggests that symptoms may be delayed relative to when an individual is infectious. A few different lines of evidence suggests this. When viral loads are measured over time in symptomatic individuals, studies show that they are at a peak on the first day of symptoms, suggesting that they were already high before symptoms started [@woelfel_clinical_2020]. Secondly, detailed contact tracing studies that have tracked transmission chains where the infector and the infectee are both known have found the _serial interval_, which is the time between symptom onset in the infector and infectee, is sometimes less than the incubation period. This means there must be presymptomatic transmission. We model this by separating the exposed stage into two classes, the latter of which can transmit. A wide range of values for the proportion of all transmission that is pre-symptomatic have been estimated (12%-62%), so we choose an intermediate value of 25%, consistent with [@liu_contribution_2020]. Assuming that pre-symptomatic infections have the same transmission rate as symptomatic infection during the period they are infections, this proportion corresponds to the quantity $(1/a_0)/((1/a_0)+(1/(p_1+\gamma_1)))$. A related line of evidence for the presence of presymptomatic infection is that the average length of the serial interval is quite close to the average length of the incubation period in a few studies. This suggests either a very short symptomatic+infectious period, or, significant pre-symptomatic transmission. 



__Table 4__:  Additional parameters for COVID-19 clinical progression, and literature sources, from March 21 2020 model update

Quantity                                     Parameter                               Value        Source       
--------------------------------------       ---------------------                   ----------   --------------------------------------------------
Portion of asymptomatic infections           $f$                                     30%           [@bi_epidemiology_2020; @mizumoto_estimating_2020; @nishiura_estimation_2020]
Duration of asymptomatic infections          $1/\gamma_0$                            6 days        =[Duration of mild infection] 
Duration of pre-symptomatic infectiousness   $1/a_0$                                 2 days        [@liu_contribution_2020; @ganyani_estimating_2020; @du_serial_2020]
Serial interval                              $1/a_0+(1/2)(1/a_1+1/(p_1 + \gamma_1))$ 7 days        =[Incubation Period]+1/2[Duration of mild infection][@bi_epidemiology_2020; @wu_characteristics_2020; @li_early_2020]


### References



